# Конфигурация источников тем для блога H-Studio Business
# Фокус: автоматизация расчётов, КП, себестоимость, 1С/ERP и AI для производства

keywords:
  - "автоматизация расчетов"
  - "расчет себестоимости"
  - "автоматизация КП"
  - "коммерческие предложения"
  - "конфигуратор КП"
  - "конфигуратор коммерческих предложений"
  - "ошибки в расчетах"
  - "контроль маржинальности"
  - "расчеты в производстве"
  - "производственная автоматизация"
  - "автоматизация производства"
  - "автоматизация документооборота"
  - "электронное согласование документов"
  - "интеграция с 1С"
  - "интеграция ERP"
  - "1С производство"
  - "ERP для производства"
  - "AI для производства"
  - "AI-аналитика"
  - "аналитика в производстве"
  - "цифровизация производства"

# Усиление тем с определёнными словами в заголовке
title_contains:
  "себестоимость": 1.35
  "маржинальность": 1.3
  "коммерческ": 1.3      # коммерческое предложение / коммерческие
  "КП": 1.3
  "конфигуратор": 1.35
  "ошибки в расчетах": 1.4
  "1С": 1.35
  "ERP": 1.3
  "документооборот": 1.35
  "согласован": 1.3      # согласование/согласования
  "производств": 1.25
  "AI": 1.25
  "аналитика": 1.2

# RSS-источники для поиска актуальных тем
rss:
  - "https://news.google.com/rss/search?q=автоматизация+расчетов+себестоимости"
  - "https://news.google.com/rss/search?q=конфигуратор+коммерческих+предложений"
  - "https://news.google.com/rss/search?q=производственная+автоматизация"
  - "https://news.google.com/rss/search?q=автоматизация+документооборота"
  - "https://news.google.com/rss/search?q=интеграция+1С+ERP"
  - "https://news.google.com/rss/search?q=AI+аналитика+производство"

